# 1. docker build -t complex:client  -f Dockerfile.dev .
# 2. docker run -p 3000:3000 complex:client


FROM node:lts-alpine

WORKDIR "/app"

COPY ./package.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]